### ISSUE TITLE
Determine (and implement) sync frequency for iana-registries

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/iana-registries-sync#1]
The https://github.com/larseggert/iana-assignments mirror seems to be synching via rsync every hour.

Currently we rsync every 24 hours. Given rsync is a sync protocol and probably won't be a burden to IANA, we could potentially shorten the sync frequency to make data updates available earlier, e.g. every hour.

This issue will have to be discussed with @rjsparks .

**Comment by rjsparks** [comment]
Hourly seems fine.

**Comment by ronaldtse** [comment]
Updated, thanks @rjsparks !
